require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'bin/*'
    - 'config.ru'